<?php
// $_item = $block->getItem();
// $product = $_item->getProduct();
$object_Manager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $object_Manager->get('Magento\Framework\Registry')->registry('current_product');//get current product

$productId = $product->getData('entity_id');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $products = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
    $myCustomAttrVal = $products->getData('pre_order');
    $preOrder = '';
    if($myCustomAttrVal == 1)
    {
        $buttonTitle = __('Pre-Order');
        $action = __('disabled');
    }
    else{
        $buttonTitle = __('Add To Cart');
        $action = __('disabled');
    }
?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
